=== jdrequena/broker_produccion/broker_produccion/xsd/util/product_items_schema.xsd
<?xml version='1.0' encoding='UTF-8'?>
<xsd:schema version="1.0" targetNamespace="http://tigo.com/resources/util/productItem/v1/schema" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:sch="http://tigo.com/resources/util/productItem/v1/schema">
   <xsd:element name="productItemList" type="sch:productItemList_type"/>
   <xsd:complexType name="productItemList_type">
      <xsd:sequence>
         <xsd:element name="productItem" type="sch:productItem_type" minOccurs="0" maxOccurs="unbounded"/>
      </xsd:sequence>
   </xsd:complexType>
   <xsd:complexType name="productItem_type">
      <xsd:sequence>
         <xsd:element name="idRoot" type="xsd:string" minOccurs="0"/>
         <xsd:element name="idItem" type="xsd:string" minOccurs="0"/>
         <xsd:element name="action" type="xsd:string" minOccurs="0"/>
         <xsd:element name="type" type="xsd:string" minOccurs="0"/>
      </xsd:sequence>
   </xsd:complexType>
</xsd:schema>

=== jdrequena/broker_produccion/broker_produccion/public_html/Transformation_OrderToProductItems-Target.xml
<?xml version='1.0' encoding='UTF-8'?>
<ns14:productItemList xmlns:ns14="http://tigo.com/resources/util/productItem/v1/schema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://tigo.com/resources/util/productItem/v1/schema file:/D:/Development/soa_project/regional_ws/Broker/O2/xsd/util/product_items_schema.xsd">
   <productItem>
      <idItem>CODE6</idItem>
      <action/>
      <type>IN</type>
   </productItem>
   <productItem>
      <idItem>CODE15</idItem>
      <action/>
      <type>IN</type>
   </productItem>
   <productItem>
      <idItem>CODE24</idItem>
      <action/>
      <type>IN</type>
   </productItem>
</ns14:productItemList>
